### ISSUE TITLE
Plugin.SofaPython3: Compilation problem

### ISSUE THREAD

**Issue by Younesssss** [sofa-framework/plugin.SofaPython3#11]
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11_static_set':
<artificial>:(.text+0x57): undefined reference to `PyProperty_Type'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11_static_get':
<artificial>:(.text+0x83): undefined reference to `PyProperty_Type'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11_object_init':
<artificial>:(.text+0x1429): undefined reference to `PyExc_TypeError'
<artificial>:(.text+0x1435): undefined reference to `PyErr_SetString'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::cast_error::set_error() const':
<artificial>:(.text+0x1490): undefined reference to `PyExc_RuntimeError'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::detail::type_caster<bool, void>& pybind11::detail::load_type<bool, void>(pybind11::detail::type_caster<bool, void>&, pybind11::handle const&)':
<artificial>:(.text+0x1894): undefined reference to `_Py_TrueStruct'
<artificial>:(.text+0x18a1): undefined reference to `_Py_FalseStruct'
<artificial>:(.text+0x18aa): undefined reference to `_Py_NoneStruct'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::detail::type_caster<double, void>::load(pybind11::handle, bool)':
<artificial>:(.text+0x19d5): undefined reference to `PyFloat_Type'
<artificial>:(.text+0x19df): undefined reference to `PyType_IsSubtype'
<artificial>:(.text+0x19ef): undefined reference to `PyFloat_AsDouble'
<artificial>:(.text+0x1a27): undefined reference to `PyErr_Occurred'
<artificial>:(.text+0x1a39): undefined reference to `PyExc_TypeError'
<artificial>:(.text+0x1a41): undefined reference to `PyErr_ExceptionMatches'
<artificial>:(.text+0x1a4a): undefined reference to `PyErr_Clear'
<artificial>:(.text+0x1a57): undefined reference to `PyNumber_Check'
<artificial>:(.text+0x1a63): undefined reference to `PyNumber_Float'
<artificial>:(.text+0x1a6b): undefined reference to `PyErr_Clear'
<artificial>:(.text+0x1ab1): undefined reference to `PyErr_Clear'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > pybind11::cast<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, 0>(pybind11::handle const&)':
<artificial>:(.text+0x1b48): undefined reference to `PyUnicode_AsEncodedString'
<artificial>:(.text+0x1b5c): undefined reference to `PyBytes_AsString'
<artificial>:(.text+0x1b67): undefined reference to `PyBytes_Size'
<artificial>:(.text+0x1c51): undefined reference to `PyErr_Clear'
<artificial>:(.text+0x1cab): undefined reference to `PyBytes_AsString'
<artificial>:(.text+0x1cbb): undefined reference to `PyBytes_Size'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11_meta_getattro':
<artificial>:(.text+0x236d): undefined reference to `_PyType_Lookup'
<artificial>:(.text+0x2379): undefined reference to `PyType_Type'
<artificial>:(.text+0x23a3): undefined reference to `PyInstanceMethod_Type'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::detail::translate_exception(std::__exception_ptr::exception_ptr)':
<artificial>:(.text+0x24bf): undefined reference to `PyExc_RuntimeError'
<artificial>:(.text+0x24ce): undefined reference to `PyErr_SetString'
<artificial>:(.text+0x24f4): undefined reference to `PyExc_RuntimeError'
<artificial>:(.text+0x24fc): undefined reference to `PyErr_SetString'
<artificial>:(.text+0x2536): undefined reference to `PyExc_ValueError'
<artificial>:(.text+0x253e): undefined reference to `PyErr_SetString'
<artificial>:(.text+0x2558): undefined reference to `PyExc_IndexError'
<artificial>:(.text+0x2560): undefined reference to `PyErr_SetString'
<artificial>:(.text+0x259d): undefined reference to `PyExc_ValueError'
<artificial>:(.text+0x25a5): undefined reference to `PyErr_SetString'
<artificial>:(.text+0x25c2): undefined reference to `PyExc_ValueError'
<artificial>:(.text+0x25ca): undefined reference to `PyErr_SetString'
<artificial>:(.text+0x2607): undefined reference to `PyExc_ValueError'
<artificial>:(.text+0x260f): undefined reference to `PyErr_SetString'
<artificial>:(.text+0x262c): undefined reference to `PyExc_MemoryError'
<artificial>:(.text+0x2634): undefined reference to `PyErr_SetString'
<artificial>:(.text+0x269a): undefined reference to `PyErr_Restore'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::capsule::capsule(void const*, void (*)(void*))::{lambda(_object*)#1}::_FUN(_object*)':
<artificial>:(.text+0x296a): undefined reference to `PyCapsule_GetContext'
<artificial>:(.text+0x2977): undefined reference to `PyCapsule_GetPointer'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::tuple::tuple(unsigned long)':
<artificial>:(.text+0x2a0d): undefined reference to `PyTuple_New'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::str::str(char const*)':
<artificial>:(.text+0x2a5d): undefined reference to `PyUnicode_FromString'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::str::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >() const':
<artificial>:(.text+0x2ac8): undefined reference to `PyUnicode_AsUTF8String'
<artificial>:(.text+0x2af3): undefined reference to `PyBytes_AsStringAndSize'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::detail::accessor<pybind11::detail::accessor_policies::str_attr>::get_cache() const':
<artificial>:(.text+0x2b99): undefined reference to `PyObject_GetAttrString'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::detail::type_caster_generic::try_load_foreign_module_local(pybind11::handle)':
<artificial>:(.text+0x2c2f): undefined reference to `PyObject_HasAttrString'
<artificial>:(.text+0x2c5b): undefined reference to `PyObject_GetAttrString'
<artificial>:(.text+0x2c73): undefined reference to `PyCapsule_GetName'
<artificial>:(.text+0x2c7e): undefined reference to `PyCapsule_GetPointer'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::detail::get_internals()':
<artificial>:(.text+0x2df1): undefined reference to `PyGILState_Ensure'
<artificial>:(.text+0x2dfa): undefined reference to `PyEval_GetBuiltins'
<artificial>:(.text+0x2e49): undefined reference to `PyUnicode_DecodeUTF8'
<artificial>:(.text+0x2e7b): undefined reference to `PyTuple_New'
<artificial>:(.text+0x2ea3): undefined reference to `PyObject_CallObject'
<artificial>:(.text+0x301e): undefined reference to `PyEval_InitThreads'
<artificial>:(.text+0x3023): undefined reference to `PyThreadState_Get'
<artificial>:(.text+0x302f): undefined reference to `PyThread_tss_alloc'
<artificial>:(.text+0x304f): undefined reference to `PyThread_tss_create'
<artificial>:(.text+0x306a): undefined reference to `PyThread_tss_set'
<artificial>:(.text+0x3089): undefined reference to `PyCapsule_New'
<artificial>:(.text+0x30a1): undefined reference to `PyUnicode_FromString'
<artificial>:(.text+0x30cb): undefined reference to `PyObject_SetItem'
<artificial>:(.text+0x312b): undefined reference to `PyUnicode_FromString'
<artificial>:(.text+0x3132): undefined reference to `PyType_Type'
<artificial>:(.text+0x318e): undefined reference to `PyProperty_Type'
<artificial>:(.text+0x31ba): undefined reference to `PyType_Ready'
<artificial>:(.text+0x31e5): undefined reference to `PyObject_SetAttrString'
<artificial>:(.text+0x323a): undefined reference to `PyUnicode_FromString'
<artificial>:(.text+0x32bc): undefined reference to `PyType_Ready'
<artificial>:(.text+0x32e7): undefined reference to `PyObject_SetAttrString'
<artificial>:(.text+0x333e): undefined reference to `PyUnicode_FromString'
<artificial>:(.text+0x33ae): undefined reference to `PyBaseObject_Type'
<artificial>:(.text+0x33e5): undefined reference to `PyType_Ready'
<artificial>:(.text+0x3410): undefined reference to `PyObject_SetAttrString'
<artificial>:(.text+0x3460): undefined reference to `PyGILState_Release'
<artificial>:(.text+0x34bd): undefined reference to `PyObject_GetItem'
<artificial>:(.text+0x351d): undefined reference to `PyCapsule_Type'
<artificial>:(.text+0x3554): undefined reference to `PyObject_GetItem'
<artificial>:(.text+0x3593): undefined reference to `PyCapsule_GetName'
<artificial>:(.text+0x359e): undefined reference to `PyCapsule_GetPointer'
<artificial>:(.text+0x3644): undefined reference to `PyGILState_Release'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::detail::type_caster_generic::src_and_type(void const*, std::type_info const&, std::type_info const*) [clone .constprop.31]':
<artificial>:(.text+0x3d2b): undefined reference to `PyExc_TypeError'
<artificial>:(.text+0x3d38): undefined reference to `PyErr_SetString'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::cpp_function::initialize_generic(pybind11::detail::function_record*, char const*, std::type_info const* const*, unsigned long)':
<artificial>:(.text+0x3ee3): undefined reference to `PyTuple_New'
<artificial>:(.text+0x3f03): undefined reference to `PyObject_CallObject'
<artificial>:(.text+0x43e0): undefined reference to `PyInstanceMethod_Type'
<artificial>:(.text+0x43ed): undefined reference to `PyCFunction_Type'
<artificial>:(.text+0x43fa): undefined reference to `_Py_NoneStruct'
<artificial>:(.text+0x4450): undefined reference to `PyCapsule_New'
<artificial>:(.text+0x446b): undefined reference to `PyCapsule_SetContext'
<artificial>:(.text+0x448c): undefined reference to `PyObject_HasAttrString'
<artificial>:(.text+0x44a5): undefined reference to `PyObject_HasAttrString'
<artificial>:(.text+0x44bc): undefined reference to `PyCFunction_NewEx'
<artificial>:(.text+0x4914): undefined reference to `PyUnicode_AsEncodedString'
<artificial>:(.text+0x4928): undefined reference to `PyBytes_AsString'
<artificial>:(.text+0x4935): undefined reference to `PyBytes_Size'
<artificial>:(.text+0x4aa8): undefined reference to `PyCFunction_Type'
<artificial>:(.text+0x4ac6): undefined reference to `PyCapsule_GetName'
<artificial>:(.text+0x4ad1): undefined reference to `PyCapsule_GetPointer'
<artificial>:(.text+0x4bf9): undefined reference to `PyInstanceMethod_New'
<artificial>:(.text+0x4c3a): undefined reference to `PyCFunction_NewEx'
<artificial>:(.text+0x4e82): undefined reference to `PyCFunction_NewEx'
<artificial>:(.text+0x4f89): undefined reference to `PyErr_Clear'
<artificial>:(.text+0x5025): undefined reference to `PyBytes_AsString'
<artificial>:(.text+0x5039): undefined reference to `PyBytes_Size'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::cpp_function::initialize<pybind11::detail::all_type_info_get_cache(_typeobject*)::{lambda(pybind11::handle)#1}, void, pybind11::handle>(pybind11::detail::all_type_info_get_cache(_typeobject*)::{lambda(pybind11::handle)#1}&&, void (*)(pybind11::handle))::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call)':
<artificial>:(.text+0x5a99): undefined reference to `_Py_NoneStruct'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::gil_scoped_acquire::dec_ref()':
<artificial>:(.text+0x5b38): undefined reference to `PyThreadState_Clear'
<artificial>:(.text+0x5b3d): undefined reference to `PyThreadState_DeleteCurrent'
<artificial>:(.text+0x5b50): undefined reference to `PyThread_tss_set'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::gil_scoped_acquire::gil_scoped_acquire()':
<artificial>:(.text+0x5bb4): undefined reference to `PyThread_tss_get'
<artificial>:(.text+0x5bc1): undefined reference to `_PyThreadState_UncheckedGet'
<artificial>:(.text+0x5bd6): undefined reference to `PyEval_AcquireThread'
<artificial>:(.text+0x5bf1): undefined reference to `PyGILState_GetThisThreadState'
<artificial>:(.text+0x5c05): undefined reference to `PyThreadState_New'
<artificial>:(.text+0x5c21): undefined reference to `PyThread_tss_set'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::error_already_set::~error_already_set()':
<artificial>:(.text+0x5c67): undefined reference to `PyErr_Fetch'
<artificial>:(.text+0x5cd5): undefined reference to `PyErr_Restore'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::error_already_set::~error_already_set()':
<artificial>:(.text+0x5d77): undefined reference to `PyErr_Fetch'
<artificial>:(.text+0x5de5): undefined reference to `PyErr_Restore'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11_meta_setattro':
<artificial>:(.text+0x5e62): undefined reference to `_PyType_Lookup'
<artificial>:(.text+0x5e76): undefined reference to `PyType_Type'
<artificial>:(.text+0x5eae): undefined reference to `PyObject_IsInstance'
<artificial>:(.text+0x5ebd): undefined reference to `PyObject_IsInstance'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::detail::all_type_info(_typeobject*)':
<artificial>:(.text+0x64c7): undefined reference to `PyWeakref_NewRef'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::detail::instance::allocate_layout()':
<artificial>:(.text+0x67c1): undefined reference to `PyMem_Calloc'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::detail::type_caster_generic::cast(void const*, pybind11::return_value_policy, pybind11::handle, pybind11::detail::type_info const*, void* (*)(void const*), void* (*)(void const*), void const*) [clone .constprop.9]':
<artificial>:(.text+0x69b3): undefined reference to `_Py_NoneStruct'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::cpp_function::initialize<sofapython3::pybind11_init_Simulation(pybind11::module&)::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)#6}, pybind11::object, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, pybind11::name, pybind11::scope, pybind11::sibling, char const*>(sofapython3::pybind11_init_Simulation(pybind11::module&)::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)#6}&&, pybind11::object (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&, char const* const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call)':
<artificial>:(.text+0x6aad): undefined reference to `PyUnicode_AsEncodedString'
<artificial>:(.text+0x6ac1): undefined reference to `PyBytes_AsString'
<artificial>:(.text+0x6acc): undefined reference to `PyBytes_Size'
<artificial>:(.text+0x6d73): undefined reference to `_Py_NoneStruct'
<artificial>:(.text+0x6d94): undefined reference to `PyBytes_AsString'
<artificial>:(.text+0x6da8): undefined reference to `PyBytes_Size'
<artificial>:(.text+0x6e51): undefined reference to `PyErr_Clear'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::detail::get_type_info(_typeobject*)':
<artificial>:(.text+0x72f7): undefined reference to `PyWeakref_NewRef'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::cpp_function::dispatcher(_object*, _object*, _object*)':
<artificial>:(.text+0x77fc): undefined reference to `PyCapsule_GetPointer'
<artificial>:(.text+0x78cb): undefined reference to `PyDict_GetItemString'
<artificial>:(.text+0x7c09): undefined reference to `PyDict_Size'
<artificial>:(.text+0x7d6a): undefined reference to `_Py_NoneStruct'
<artificial>:(.text+0x85dd): undefined reference to `PyDict_GetItemString'
<artificial>:(.text+0x8606): undefined reference to `PyDict_Copy'
<artificial>:(.text+0x8642): undefined reference to `PyDict_DelItemString'
<artificial>:(.text+0x8c69): undefined reference to `_Py_NoneStruct'
<artificial>:(.text+0x907c): undefined reference to `PyDict_New'
<artificial>:(.text+0x90d1): undefined reference to `_Py_NotImplementedStruct'
<artificial>:(.text+0x91fe): undefined reference to `PyTuple_SetItem'
<artificial>:(.text+0x9299): undefined reference to `PyTuple_Size'
<artificial>:(.text+0x92b1): undefined reference to `PyTuple_GetItem'
<artificial>:(.text+0x92c9): undefined reference to `PyObject_Repr'
<artificial>:(.text+0x9368): undefined reference to `PyTuple_Size'
<artificial>:(.text+0x941c): undefined reference to `PyDict_Size'
<artificial>:(.text+0x948b): undefined reference to `PyDict_Next'
<artificial>:(.text+0x957c): undefined reference to `PyDict_Next'
<artificial>:(.text+0x9643): undefined reference to `PyObject_CallObject'
<artificial>:(.text+0x9686): undefined reference to `PyObject_Str'
<artificial>:(.text+0x9707): undefined reference to `PyExc_TypeError'
<artificial>:(.text+0x9717): undefined reference to `PyErr_SetString'
<artificial>:(.text+0x9cb9): undefined reference to `PyExc_TypeError'
<artificial>:(.text+0x9cca): undefined reference to `PyErr_SetString'
<artificial>:(.text+0x9d32): undefined reference to `PyExc_TypeError'
<artificial>:(.text+0x9d42): undefined reference to `PyErr_SetString'
<artificial>:(.text+0x9fe6): undefined reference to `PyExc_SystemError'
<artificial>:(.text+0x9ff5): undefined reference to `PyErr_SetString'
<artificial>:(.text+0xa050): undefined reference to `PyErr_Restore'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11_object_dealloc':
<artificial>:(.text+0xa934): undefined reference to `PyObject_ClearWeakRefs'
<artificial>:(.text+0xa93c): undefined reference to `_PyObject_GetDictPtr'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::detail::loader_life_support::add_patient(pybind11::handle)':
<artificial>:(.text+0xaf3b): undefined reference to `PyList_Append'
<artificial>:(.text+0xaf56): undefined reference to `PyList_New'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `bool pybind11::detail::type_caster_generic::load_impl<pybind11::detail::type_caster_generic>(pybind11::handle, bool)':
<artificial>:(.text+0xb01f): undefined reference to `_Py_NoneStruct'
<artificial>:(.text+0xb03d): undefined reference to `PyType_IsSubtype'
<artificial>:(.text+0xb298): undefined reference to `PyType_IsSubtype'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::cpp_function::initialize<sofapython3::pybind11_init_Simulation(pybind11::module&)::{lambda(sofa::simulation::Node*)#8}, void, sofa::simulation::Node*, pybind11::name, pybind11::scope, pybind11::sibling>(sofapython3::pybind11_init_Simulation(pybind11::module&)::{lambda(sofa::simulation::Node*)#8}&&, void (*)(sofa::simulation::Node*), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call)':
<artificial>:(.text+0xb47a): undefined reference to `_Py_NoneStruct'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::cpp_function::initialize<sofapython3::pybind11_init_Simulation(pybind11::module&)::{lambda(sofa::simulation::Node*)#9}, void, sofa::simulation::Node*, pybind11::name, pybind11::scope, pybind11::sibling>(sofapython3::pybind11_init_Simulation(pybind11::module&)::{lambda(sofa::simulation::Node*)#9}&&, void (*)(sofa::simulation::Node*), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call)':
<artificial>:(.text+0xb4fa): undefined reference to `_Py_NoneStruct'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::cpp_function::initialize<sofapython3::pybind11_init_Simulation(pybind11::module&)::{lambda(sofa::simulation::Node*)#7}, void, sofa::simulation::Node*, pybind11::name, pybind11::scope, pybind11::sibling, char const*>(sofapython3::pybind11_init_Simulation(pybind11::module&)::{lambda(sofa::simulation::Node*)#7}&&, void (*)(sofa::simulation::Node*), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&, char const* const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call)':
<artificial>:(.text+0xb5bd): undefined reference to `_Py_NoneStruct'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::cpp_function::initialize<sofapython3::pybind11_init_Simulation(pybind11::module&)::{lambda(sofa::simulation::Node*)#5}, void, sofa::simulation::Node*, pybind11::name, pybind11::scope, pybind11::sibling, char const*>(sofapython3::pybind11_init_Simulation(pybind11::module&)::{lambda(sofa::simulation::Node*)#5}&&, void (*)(sofa::simulation::Node*), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&, char const* const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call)':
<artificial>:(.text+0xb65a): undefined reference to `_Py_NoneStruct'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::cpp_function::initialize<sofapython3::pybind11_init_Simulation(pybind11::module&)::{lambda(sofa::simulation::Node*)#4}, void, sofa::simulation::Node*, pybind11::name, pybind11::scope, pybind11::sibling>(sofapython3::pybind11_init_Simulation(pybind11::module&)::{lambda(sofa::simulation::Node*)#4}&&, void (*)(sofa::simulation::Node*), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call)':
<artificial>:(.text+0xb6ec): undefined reference to `_Py_NoneStruct'
/tmp/ccWMVR0G.ltrans0.ltrans.o:<artificial>:(.text+0xb76a): more undefined references to `_Py_NoneStruct' follow
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::cpp_function::initialize<sofapython3::pybind11_init_Simulation(pybind11::module&)::{lambda(sofa::simulation::Node*, double)#2}, void, sofa::simulation::Node*, double, pybind11::name, pybind11::scope, pybind11::sibling, char const*>(sofapython3::pybind11_init_Simulation(pybind11::module&)::{lambda(sofa::simulation::Node*, double)#2}&&, void (*)(sofa::simulation::Node*, double), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&, char const* const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call)':
<artificial>:(.text+0xb80b): undefined reference to `PyFloat_Type'
<artificial>:(.text+0xb815): undefined reference to `PyType_IsSubtype'
<artificial>:(.text+0xb821): undefined reference to `PyFloat_AsDouble'
<artificial>:(.text+0xb861): undefined reference to `_Py_NoneStruct'
<artificial>:(.text+0xb891): undefined reference to `PyErr_Clear'
<artificial>:(.text+0xb8b7): undefined reference to `PyErr_Occurred'
<artificial>:(.text+0xb8cd): undefined reference to `PyExc_TypeError'
<artificial>:(.text+0xb8d5): undefined reference to `PyErr_ExceptionMatches'
<artificial>:(.text+0xb8de): undefined reference to `PyErr_Clear'
<artificial>:(.text+0xb8eb): undefined reference to `PyNumber_Check'
<artificial>:(.text+0xb8f7): undefined reference to `PyNumber_Float'
<artificial>:(.text+0xb8ff): undefined reference to `PyErr_Clear'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::cpp_function::initialize<sofapython3::pybind11_init_Simulation(pybind11::module&)::{lambda(sofa::simulation::Node*)#1}, void, sofa::simulation::Node*, pybind11::name, pybind11::scope, pybind11::sibling, char const*>(sofapython3::pybind11_init_Simulation(pybind11::module&)::{lambda(sofa::simulation::Node*)#1}&&, void (*)(sofa::simulation::Node*), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&, char const* const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call)':
<artificial>:(.text+0xb9ba): undefined reference to `_Py_NoneStruct'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `PyInit_Simulation':
<artificial>:(.text+0xba4b): undefined reference to `Py_GetVersion'
<artificial>:(.text+0xbae4): undefined reference to `PyModule_Create2'
<artificial>:(.text+0xbb4f): undefined reference to `PyUnicode_DecodeUTF8'
<artificial>:(.text+0xbb80): undefined reference to `PyObject_SetAttrString'
<artificial>:(.text+0xbb9f): undefined reference to `_Py_NoneStruct'
<artificial>:(.text+0xbbb4): undefined reference to `PyObject_GetAttrString'
<artificial>:(.text+0xbc82): undefined reference to `PyObject_GetAttrString'
<artificial>:(.text+0xbd4c): undefined reference to `PyObject_GetAttrString'
<artificial>:(.text+0xbe16): undefined reference to `PyObject_GetAttrString'
<artificial>:(.text+0xbed5): undefined reference to `PyObject_GetAttrString'
/tmp/ccWMVR0G.ltrans0.ltrans.o:<artificial>:(.text+0xbf9f): more undefined references to `PyObject_GetAttrString' follow
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `PyInit_Simulation':
<artificial>:(.text+0xc2d3): undefined reference to `_Py_NoneStruct'
<artificial>:(.text+0xc326): undefined reference to `PyExc_ImportError'
<artificial>:(.text+0xc340): undefined reference to `PyErr_Format'
<artificial>:(.text+0xc361): undefined reference to `PyErr_Clear'
<artificial>:(.text+0xc381): undefined reference to `PyErr_Clear'
<artificial>:(.text+0xc3a1): undefined reference to `PyErr_Clear'
<artificial>:(.text+0xc3c1): undefined reference to `PyErr_Clear'
<artificial>:(.text+0xc3e1): undefined reference to `PyErr_Clear'
/tmp/ccWMVR0G.ltrans0.ltrans.o:<artificial>:(.text+0xc401): more undefined references to `PyErr_Clear' follow
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `PyInit_Simulation':
<artificial>:(.text+0xca31): undefined reference to `PyExc_ImportError'
<artificial>:(.text+0xca39): undefined reference to `PyErr_SetString'
<artificial>:(.text+0xca65): undefined reference to `PyExc_ImportError'
<artificial>:(.text+0xca6d): undefined reference to `PyErr_SetString'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::cast_error::set_error() const':
<artificial>:(.text+0x149c): undefined reference to `PyErr_SetString'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::detail::instance::deallocate_layout()':
<artificial>:(.text+0x23d5): undefined reference to `PyMem_Free'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::module::add_object(char const*, pybind11::handle, bool) [clone .constprop.60]':
<artificial>:(.text+0x299d): undefined reference to `PyModule_AddObject'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::gil_scoped_acquire::~gil_scoped_acquire()':
<artificial>:(.text+0x5b82): undefined reference to `PyEval_SaveThread'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::detail::error_string[abi:cxx11]()':
<artificial>:(.text.unlikely+0x144): undefined reference to `PyErr_Occurred'
<artificial>:(.text.unlikely+0x150): undefined reference to `PyExc_RuntimeError'
<artificial>:(.text.unlikely+0x15f): undefined reference to `PyErr_SetString'
<artificial>:(.text.unlikely+0x18d): undefined reference to `PyErr_Fetch'
<artificial>:(.text.unlikely+0x267): undefined reference to `PyObject_Str'
<artificial>:(.text.unlikely+0x2de): undefined reference to `PyErr_NormalizeException'
<artificial>:(.text.unlikely+0x301): undefined reference to `PyException_SetTraceback'
<artificial>:(.text.unlikely+0x353): undefined reference to `PyFrame_GetLineNumber'
<artificial>:(.text.unlikely+0x5ba): undefined reference to `PyErr_Restore'
<artificial>:(.text.unlikely+0x782): undefined reference to `PyErr_Restore'
/tmp/ccWMVR0G.ltrans0.ltrans.o: In function `pybind11::error_already_set::error_already_set()':
<artificial>:(.text.unlikely+0x804): undefined reference to `PyErr_Fetch'
collect2: error: ld returned 1 exit status
external_directories/plugin.SofaPython3/bindings/Sofa/src/SofaPython3/Sofa/Simulation/CMakeFiles/Bindings.Sofa.Simulation.dir/build.make:102: recipe for target 'lib/site-packages/Sofa/Simulation.cpython-37m-x86_64-linux-gnu.so' failed
make[2]: *** [lib/site-packages/Sofa/Simulation.cpython-37m-x86_64-linux-gnu.so] Error 1
CMakeFiles/Makefile2:11872: recipe for target 'external_directories/plugin.SofaPython3/bindings/Sofa/src/SofaPython3/Sofa/Simulation/CMakeFiles/Bindings.Sofa.Simulation.dir/all' failed
make[1]: *** [external_directories/plugin.SofaPython3/bindings/Sofa/src/SofaPython3/Sofa/Simulation/CMakeFiles/Bindings.Sofa.Simulation.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by marques-bruno** [comment]
Hi @Younesssss can you:
1. send me the output of this command on your system:
`apt -qq list --installed python3.7-dev `
2. in your cmake configuration, what is the content of the PYTHON_EXECUTABLE variable?
3. how did you install pybind11 ? did you install it from the sources in the pybind11 github repository? and if so, which version did you checkout?

**Comment by Younesssss** [comment]
~ apt -qq list --installed python3.7-dev
python3.7-dev/bionic-updates,now 3.7.5-2~18.04 amd64 [installed]
![Screenshot from 2020-06-12 17-09-35](https://user-images.githubusercontent.com/24458481/84517424-97033900-accf-11ea-8b47-9c0b086df38e.png)

**Comment by Younesssss** [comment]
pybind repo : git@github.com:pybind/pybind11.git. The version I took the last one in October

**Comment by Younesssss** [comment]
commit e107fc2a054fe3c71bbd8c4ed2539fdb80e9f1b5 (HEAD -> master, origin/master, origin/HEAD)
Author: Isuru Fernando <isuruf@gmail.com>
Date:   Sun Apr 26 14:56:10 2020 +0000

    Fix setuptools record of headers

Just took an update remove the old pybind11 run it agin `sudo make install ` and compile Sofa again and same Error
